config/routes.rb
TruelyIsThatRight::Application.routes.draw do

  # get "responses/new", as: 'new_response'
  # post 'responses' => 'responses#create'

  resources :responses, :only => [:new, :create]

  resources :questions

  match '/auth/:provider/callback', :to => 'sessions#create' 
  match '/auth/failure', to: redirect('/')
  match '/signout', to: 'sessions#destroy', as: 'signout'

  root :to => 'static_pages#home'
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :statement, :fact_or_fiction, :user_id

  has_many :responses
  has_many :users, through: :responses
  belongs_to :user 

  before_validation :downcase_statement 

  validates :statement, presence: true
  validates :statement, length: { minimum: 5, maximum: 255 }
  validates :statement, uniqueness: { case_sensitive: true }
  validates :fact_or_fiction, inclusion: { in: [true, false] }

  # Used by will_paginate to set no. users per page
  self.per_page = 15

  def self.random_question
    Question.first(order: 'RANDOM()')
  end

  def self.get_random_outstanding_question_not_created_by(user)
    self.find_by_sql [" SELECT *
                        FROM questions
                        WHERE user_id <> ?
                        AND id NOT IN
                          ( SELECT question_id
                            FROM responses
                            WHERE user_id = ?
                          )
                        ORDER BY RANDOM() LIMIT 1
                      ", 
                        user.id,
                        user.id
                     ]
  end

  def self.questions_available_for_user(user)
    Question.where("user_id != ?", user.id).count
  end
  
  private

    def downcase_statement
      self.statement = statement.downcase
    end
end

app/models/response.rb
class Response < ActiveRecord::Base
  
  attr_accessible :correct, :question_id, :user_id, :user_response

  belongs_to :user
  belongs_to :question

  validates :user_response, inclusion: { in: [true, false] }

  def is_correct?
    user_response == Question.find(question_id).fact_or_fiction
  end

  def self.num_questions_answered(user)
    Response.find_all_by_user_id(user).count
  end

  def self.num_correctly_answered(user)
    Response.find_all_by_user_id_and_correct(user, true).count
  end

  def self.percentage_correctly_answered(user)
    # need to use .to_f on the denominator to get a non-zero value from the division
    result = ( num_correctly_answered(user) / num_questions_answered(user).to_f ) * 100 
    result.nan? ? "0" : sprintf('%.0f', result)
  end

  def self.percentage_available_questions_answered(user)
    result = ( num_questions_answered(user) / Question.questions_available_for_user(user).to_f ) * 100
    result.nan? ? "0" : sprintf('%.0f', result)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid

  has_many :responses
  has_many :questions, through: :responses
  has_many :questions

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  #Will use this to add Twitter OAuth authentication
  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    # user = User.where(:provider => auth.provider, :uid => auth.uid).first
    # if user
    #   return user
    # else
    #   registered_user = User.where(:email => auth.uid + "@twitter.com").first
    #   if registered_user
    #     return registered_user
    #   else
    #     user = User.create(name:auth.info.name,
    #       provider:auth.provider,
    #       uid:auth.uid,
    #       email:auth.uid+"@twitter.com",
    #       password:Devise.friendly_token[0,20],
    #     )
    #   end
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # http://stackoverflow.com/questions/1168144/
  # having-to-call-render-layout-false-to-correctly-render-js-erb-template-in
  before_filter proc { |controller| (controller.action_has_layout = false) if controller.request.xhr? }

  def authorized
    redirect_to root_path, :alert => "Please sign in to complete this request" unless current_user
  end

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id] 
    end
    helper_method :current_user


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  before_filter :authorized, only: [:new, :create]

  def index
    @questions = Question.paginate(page: params[:page])
    # this is now in application controller as a proc so its system wide for AJAX (xhr) calls
    # render :layout => false if request.xhr?
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build(params[:question])
    if @question.save
      flash[:notice] = "Your question was added"
      respond_to do |format| 
        format.html { redirect_to root_path }
        format.json { render json: @question, status: :created }
      end
    else
      flash.now[:error] = "Something went wrong, please try again" unless request.xhr?
      respond_to do |format|
        format.html { render :new, :error => "Something went wrong, please try again." }
        format.json { render :json => { :error => @question.errors.messages}, :status => 422 }
      end   
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(params[:question])
      redirect_to questions_path, :notice => "The question has been updated"
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      redirect_to questions_path, :notice => "Question deleted"
    end
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  before_filter :authorized, only: [:new, :create]

  respond_to :html, :json

  def new
    @response = Response.new
    @question = Question.get_random_outstanding_question_not_created_by(current_user).first
  end

  def create
    # This is where we create the current_users response to the question asked 
    @response = current_user.responses.build(params[:response])
    params[:commit] == 'Fact' ? @response.user_response = true : @response.user_response = false
    @response.correct = @response.is_correct?
    if @response.save
      respond_to do |format|
        format.html { render :show }
      end
    else
      flash[:error] = "Something went wrong, please try again"
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
  def question_response_right_or_wrong
    @response.correct == true ? "right" : "wrong"
  end

  def response_statistics
    Response.percentage_correctly_answered(current_user)
  end

  def answered_statistics
    Response.percentage_available_questions_answered(current_user)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_footer.html.erb
<footer>
       <div class='background-img'> 
          
       </div> 
</footer>

app/views/layouts/_header.html.erb
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <% if current_user %>
          <%= hidden_field_tag "user-id", current_user.id %>
        <% end %>
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "London Fact or Fiction", root_path, class: "brand" %>
        <div class="container nav-collapse">
          <ul class="nav">
            <li><%= link_to raw('<i class="icon-play"></i> Play'), new_response_path, id: "start_new_game" %></li>
            <li><%= link_to raw('<i class="icon-plus"></i>Add a Question'), new_question_path, id: "add_fact_or_fiction" %></li>
          </ul>
          <ul class="nav pull-right">
            <% if current_user %>
              <li><%= link_to raw("<i class='icon-facebook-sign'></i> #{current_user.name}"), signout_path %></li>
              <li><%= link_to "Sign out", signout_path %></li>
            <% else %>
              <li><%= link_to "Sign in: ", "/auth/facebook", id: "fb_sign_in" %></li>
              <li><%= link_to raw('<i class="icon-facebook-sign icon-2x"></i>'), "/auth/facebook", id: "fb_sign_in" %></li>
              <li><%#= link_to image_tag('twitter_32.png'), "/auth/twitter" %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>London Fact or Fiction</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

  </head>
  <body class="<%= controller_name %>">

    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |type, msg| %>
        <div class="alert alert-<%= type == :notice ? "success" : "error" %> fade in">
          <button type="button" class="close" data-dismiss="alert"><i class="icon-remove-sign"></i></button>
          <%= msg %>
        </div>
      <% end %>
        <div class="row-fluid">
          <div class="span12" id="main-page">
            <%= yield %>
          </div>
        </div><!--/row-fluid-->
        <%= render 'layouts/footer' %>
    </div><!--/container-->
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <% f.label :statement %>
  <%= f.text_field :statement, placeholder: "Your London Fact or Fiction ", autofocus: true %>
  </br>
  <div class="radio-input">
    <%= f.radio_button :fact_or_fiction, true, class: "fact-fiction-radio-btn"%><%= f.label :fact_or_fiction, 'Fact', class: "fact-fiction-radio-btn-label" %>
    <%= f.radio_button :fact_or_fiction, false, class: "fact-fiction-radio-btn" %> <%= f.label :fact_or_fiction, 'Fiction', class: "fact-fiction-radio-btn-label" %><br>
  </div>
    <%= f.submit "Save", class: "btn btn-primary", id: "btn-add-question" %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Statement</h1>

<%= render 'form' %>

<%= link_to "Back", questions_path, class: "btn btn-primary" %>

app/views/questions/index.html.erb
<h1>All Questions</h1>

<%= will_paginate %>

<% @questions.each do |q| %>
  <ul class="all-statements">
    <li><%= q.statement.humanize %></li><br>
    <li><%= link_to raw('<i class="icon-edit"></i> Edit'), edit_question_path(q), class: "btn" %></li>
    <li><%= link_to '<i class="icon-minus icon-white"></i> Delete'.html_safe, q, method: :delete, confirm: 'Are you sure?', class: "btn btn-danger" %></li><br>
  </ul>
<% end %>

<%= will_paginate %>

app/views/questions/new.html.erb
<div class="flash-card">
  <h2>Add your London Fact or Fiction Statement</h2>
  <br>

  <%= render 'form' %>
</div>

app/views/responses/_form.html.erb
  <%= form_for @response do |f| %>

    <h3 class='statement'><%= @question.statement.humanize %></h3>
      <%= f.hidden_field :question_id, value: @question.id %>

    <div class="radio-btn" data-toggle="buttons-radio">
      <%= f.submit value: "Fact", id: "fact", class: "btn-large btn-response" %>
      <%= f.submit value: "Fiction", id: "fiction", class: "btn-large btn-response" %>
    </div>                      
  <% end %>

app/views/responses/_statistics.html.erb
<hr>
<h3 class="percentage-answered">
  Your statistics <br>
</h3>

<h5> 
  Answered 
</h5>

<h3>
  <%= answered_statistics %>%
</h3>

<h5 class="percentage-correctly-answered"> 
  Correctly Answered
</h5>
<h3>
  <%= response_statistics %>%
</h3>

app/views/responses/new.html.erb
<div class="flash-card">
  <% unless @question.nil? %>
    <h2>Is this fact or fiction?</h2>
    <br>
    <%= render 'form' %>
  <% else %>
    <h2>You completed London Fact or Fiction!</h2>
    <h3>(feel free to add your own)
    </h3>
  <% end %>
</div>

app/views/responses/show.html.erb
<div class="flash-card">
<h2>You got it <%= question_response_right_or_wrong %>!</h2>
  <%= render 'statistics' %>
  <%= link_to "Next", new_response_path, class: "btn-large btn-response next-question" %>
  <%= link_to "End Game", root_path, class: "btn-large btn-response end-game" %>
</div>

app/views/static_pages/home.html.erb
<h1 class='headline-title'>How well do you know London?</h1>